# Generated by Django 3.2.3 on 2023-04-15 16:39

import BLMApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYCRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_id', models.IntegerField(default=BLMApp.models.generate_unique_id, editable=False, unique=True)),
                ('add_profile_image', models.ImageField(blank=True, null=True, upload_to=BLMApp.models.getProfileImageKYC)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=20)),
                ('martial_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('id_proof_type', models.CharField(choices=[('passport', 'Passport'), ('driving_license', 'Driving License'), ('aadhaar_card', 'Aadhaar Card'), ('pan_card', 'PAN Card'), ('voter_id', 'Voter ID')], max_length=30)),
                ('id_proof_number', models.CharField(max_length=30)),
                ('id_proof_file', models.FileField(upload_to=BLMApp.models.getIdProofFile)),
                ('residental_address', models.CharField(max_length=255)),
                ('city_or_town', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('pin_code', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('kyc_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approve'), ('Rejected', 'Reject')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LoanTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=50)),
                ('loan_description', models.CharField(max_length=150)),
                ('loan_image', models.ImageField(blank=True, null=True, upload_to=BLMApp.models.getFileName)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LoanPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_plan_duration_months', models.IntegerField()),
                ('loan_plan_duration_years', models.DecimalField(decimal_places=1, editable=False, max_digits=4)),
                ('loan_interest_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BLMApp.loantypes')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_id', models.IntegerField(unique=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_on', models.DateField(auto_now_add=True, null=True)),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approve'), ('Rejected', 'Reject')], default='Pending...', max_length=20)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total_payable_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('monthly_payable_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('emi_paid', models.IntegerField()),
                ('emi_pending', models.IntegerField()),
                ('loan_plan', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BLMApp.loanplans')),
                ('loan_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BLMApp.loantypes')),
            ],
        ),
    ]
