# Generated by Django 3.2.3 on 2023-04-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLMApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyloan',
            name='loan_id',
            field=models.CharField(default='YB2023041522:14:24', editable=False, max_length=40),
        ),
    ]
