# Generated by Django 3.2.3 on 2023-04-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLMApp', '0004_alter_applyloan_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyloan',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approve'), ('Rejected', 'Reject')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='applyloan',
            name='loan_id',
            field=models.CharField(default='YB2023042247', editable=False, max_length=40),
        ),
    ]
