# Generated by Django 3.2.3 on 2023-04-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLMApp', '0007_auto_20230420_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyloan',
            name='user_name_kyc',
            field=models.CharField(default=' ', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='applyloan',
            name='loan_id',
            field=models.CharField(default='YB2023041747', editable=False, max_length=40),
        ),
    ]
